name: dominion-randomizer
version: '0.0.0.1'
category: Web
author: Tyler Lentz
maintainer: Tyler Lentz
copyright: Tyler Lentz
license: AllRightsReserved
github: tlentz/dominion-randomizer

dependencies:
- aeson
- base
- bytestring
- elm-export
- interpolate
- iproute
- network-uri
- servant
- servant-server
- string-conversions
- text
- uuid
- wai
- fast-logger
- monad-logger


library:
  source-dirs: api
  exposed-modules:
  - Api.Types
  - Api.Helper
  - Api.Server
  dependencies:
  - containers
  - data-default
  - exceptions
  - http-api-data
  - http-client
  - http-types
  - mtl
  - network
  - servant-client
  - random
  - transformers
  - fast-logger

executables:
  dominion-randomizer:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cryptonite
    - dominion-randomizer
    - wai-cors
    - warp

  code-generator:
    main: Main.hs
    source-dirs: code-generator
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dominion-randomizer
    - servant-elm
    - servant-foreign

tests:
  dominion-randomizer-tests:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - dominion-randomizer